apiVersion: v1
kind: Service
metadata:
  name: automatization-with-ansible-service
  namespace: prod
  labels:
    app.kubernetes.io/name: myapp-sprod
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: myapp-sprod
    meta.helm.sh/release-namespace: prod
spec:
  selector:
    app: automatization-with-ansible
    environment: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
