---
- name: Install Apache on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2 
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a custom homepage
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        notify:
          - Restart Apach
      
    - name: Install cowsay and lolcat
      apt:
        name:
          - cowsay
          - lolcat
        state: present

    - name: Run cowsay with color
      shell: cowsay -f dragon "Hello, DEVOPS!" | lolcat -F 0.3 -S 5e
