---
- name: Install Apache on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2 
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a custom homepage
      template:
      src: index.html.j2
      dest: /var/www/html/index.html
      notify:
    - Restart Apache
