--- ## taches

- name: Install all
  ansible.builtin.apt:
    name:

      - apache2
      - ruby
      - ruby-dev
      - lolcat
      - cowsay
    state: present
    update_cache: yes

- name: Start Apache2 service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create a custom homepage
  template:
    src:  index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache

- name: Create folder
  ansible.builtin.file: 
    path: "/{{folder_one}}"
    state: directory
  
- name: Copy Template File
  copy:
    src: templates/hello.txt.j2
    dest: "/{{folder_one}}/{{file_one}}"

- name: run cowsay
  ansible.builtin.shell:
    cmd: cowsay -f dragon "Hello, DEVOPS!" | lolcat -F 0.3 -S 5


