name: Ansible workflow

on:
  push:
    workflow_dispatch:
      branches:
        - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Ansible playbook
      run: ansible-playbook -i ansible/inventory/dev.yaml ansible/playbooks/apache-install.yaml
    
    - name: Run staging environment
        run: ansible-playbook -i ansible/inventory/staging.yaml ansible/playbooks/staging.yaml
        # Dodaj warunek, który uruchomi tylko gdy poprzedni playbook zakończy się sukcesem
        if: success()


