namei: Ansible workflow

on:
  push:
    workflow_dispatch:
      branches:
        - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Ansible playbook
       run: ansible-playbook -i inventory.ini playbooks/main.yaml
    
    - name: Set up LXD
        run: |
          sudo apt-get update
          sudo apt-get install -y lxd
          sudo lxd init --auto

