name: Ansible workflow

on:
  push:
    workflow_dispatch:
      branches:
        - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Ansible playbook
      run: ansible-playbook -i ../../inventory/dev.yaml ansible/playbooks/roles/apache/instructions-for-apache.yaml
    
